# Generated by Django 2.1.7 on 2019-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuff',
            old_name='price',
            new_name='harga',
        ),
        migrations.AddField(
            model_name='stuff',
            name='kategori',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stuff',
            name='foto',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
